2023-11-29 14:58:54: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП АВР для письма заказчику\scripts\operations.py", line 145, in get_orders
    "TYPE_OF_WORK" : get_TYPE_OF_WORK(f'{html_file}')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП АВР для письма заказчику\scripts\operations.py", line 203, in get_TYPE_OF_WORK
    types_of_works = get_types_of_works()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП АВР для письма заказчику\scripts\operations.py", line 198, in get_types_of_works
    with open('типы работ.json', 'r', encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'типы работ.json'

2023-12-04 12:21:09: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 269, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:21:30: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 269, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:23:08: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 269, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:24:39: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 269, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:29:43: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 269, in get_BS_NAME
    words = text.split("\"")
           ^^^^^^^^
IndexError: list index out of range

2023-12-04 12:33:17: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 111, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 270, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:34:28: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 112, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 271, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:36:36: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 112, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 271, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:39:22: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 112, in get_orders
    multi_BS_NAME.append(get_BS_NAME(text)) # DONE
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 278, in get_BS_NAME
    return words[1]
          ~~~~~^^^
IndexError: list index out of range

2023-12-04 12:39:43: Traceback (most recent call last):
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 151, in get_orders
    "TYPE_OF_WORK" : get_TYPE_OF_WORK(f'{html_file}')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\22186\Desktop\АТП FTTB Генератор\Project\scripts\operations.py", line 210, in get_TYPE_OF_WORK
    return types_of_works[re.findall(r'\((.*?)\)', file_name.split("\\")[-1])[0]]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

